const Routes = {
  HOME: 'HOME',
  MOVIE_DETAILS: 'MOVIE_DETAILS',
  TRAILER: 'TRAILER',
  SEARCH: 'SEARCH',
  FAVOURITES: 'FAVOURITES',
  DOWNLOADS: 'DOWNLOADS',
  MAIN_TABS: 'MAIN_TABS',
  SETTINGS: 'SETTINGS',
} as const;

export default Routes;
